#ifndef ONDRIX_CONVERSION_ONDSPTOSCALAR_ONDSPTOSCALAR_H
#define ONDRIX_CONVERSION_ONDSPTOSCALAR_ONDSPTOSCALAR_H

#include "ondrix/Conversion/Passes.h"

#endif // ONDRIX_CONVERSION_ONDSPTOSCALAR_ONDSPTOSCALAR_H
