#ifndef ONDRIX_SUPPORT_Q31TWIDDLETABLES_H
#define ONDRIX_SUPPORT_Q31TWIDDLETABLES_H

#include <cstdint>
#include <optional>

namespace ondrix {

// GENERATED by scripts/generate-q31-twiddle-tables.py; do not edit by hand.
//
// Frozen signed Q1.31 radix-2 stage twiddles W(size, index) =
// e^(-2*pi*i*index/size), quantized round-half-even with declared
// saturation at +1.0. Unlike the Q15 twiddle and DCT tables, these values
// are NOT recomputed in the compiler from binary64 cos/sin under the 2^-20
// LSB tie guard. At Q31 that guard is only 2^-51 (4.4e-16) absolute while a
// binary64 evaluation chain already errs at about 1e-16, so passing the
// guard would no longer prove that the estimate rounds like the real-valued
// definition. The tables are therefore evaluated offline at 50 decimal
// digits and frozen here, and the conversion reads them directly.
//
// The values themselves are not marginal; worst tie margin per supported
// extent, over both directions, in Q31 LSB units:
//   N =  4: 5.000000e-01
//   N =  8: 4.880248e-01
//   N = 16: 1.354557e-01
//   N = 32: 8.731015e-02
//   N = 64: 8.731015e-02
// The narrowest is about 9.1e+04 times the 2^-20 guard, so the frozen
// integers are the correctly rounded ones by a wide margin. What fails at
// Q31 is the in-compiler admissibility proof, not the coefficients.

// Largest complex extent the frozen tables cover. Stage sizes 2, 4, ...,
// kMaxQ31TwiddleExtent are tabulated, so any CFFT extent up to this bound
// is served; a larger extent must fail closed until the tables grow.
inline constexpr int64_t kMaxQ31TwiddleExtent = 64;

struct Q31TwiddleComponents {
  int32_t real;
  int32_t imaginary;
};

// Forward and inverse are stored separately rather than derived from one
// another: saturating quantization does not commute with negation at the
// +-1.0 endpoints, where the forward imaginary part is exactly -2^31 but
// its inverse counterpart saturates to 2^31 - 1.
enum class Q31TwiddleDirection { Forward, Inverse };

// Flat stage table indexed by size/2 + index, matching the recursive
// combine's W(size, index) query; slot 0 is unused.
inline constexpr Q31TwiddleComponents kForwardQ31Twiddles[kMaxQ31TwiddleExtent] = {
    {0, 0},
    {2147483647, 0},
    {2147483647, 0},
    {0, -2147483648},
    {2147483647, 0},
    {1518500250, -1518500250},
    {0, -2147483648},
    {-1518500250, -1518500250},
    {2147483647, 0},
    {1984016189, -821806413},
    {1518500250, -1518500250},
    {821806413, -1984016189},
    {0, -2147483648},
    {-821806413, -1984016189},
    {-1518500250, -1518500250},
    {-1984016189, -821806413},
    {2147483647, 0},
    {2106220352, -418953276},
    {1984016189, -821806413},
    {1785567396, -1193077991},
    {1518500250, -1518500250},
    {1193077991, -1785567396},
    {821806413, -1984016189},
    {418953276, -2106220352},
    {0, -2147483648},
    {-418953276, -2106220352},
    {-821806413, -1984016189},
    {-1193077991, -1785567396},
    {-1518500250, -1518500250},
    {-1785567396, -1193077991},
    {-1984016189, -821806413},
    {-2106220352, -418953276},
    {2147483647, 0},
    {2137142927, -210490206},
    {2106220352, -418953276},
    {2055013723, -623381598},
    {1984016189, -821806413},
    {1893911494, -1012316784},
    {1785567396, -1193077991},
    {1660027308, -1362349204},
    {1518500250, -1518500250},
    {1362349204, -1660027308},
    {1193077991, -1785567396},
    {1012316784, -1893911494},
    {821806413, -1984016189},
    {623381598, -2055013723},
    {418953276, -2106220352},
    {210490206, -2137142927},
    {0, -2147483648},
    {-210490206, -2137142927},
    {-418953276, -2106220352},
    {-623381598, -2055013723},
    {-821806413, -1984016189},
    {-1012316784, -1893911494},
    {-1193077991, -1785567396},
    {-1362349204, -1660027308},
    {-1518500250, -1518500250},
    {-1660027308, -1362349204},
    {-1785567396, -1193077991},
    {-1893911494, -1012316784},
    {-1984016189, -821806413},
    {-2055013723, -623381598},
    {-2106220352, -418953276},
    {-2137142927, -210490206},
};

inline constexpr Q31TwiddleComponents kInverseQ31Twiddles[kMaxQ31TwiddleExtent] = {
    {0, 0},
    {2147483647, 0},
    {2147483647, 0},
    {0, 2147483647},
    {2147483647, 0},
    {1518500250, 1518500250},
    {0, 2147483647},
    {-1518500250, 1518500250},
    {2147483647, 0},
    {1984016189, 821806413},
    {1518500250, 1518500250},
    {821806413, 1984016189},
    {0, 2147483647},
    {-821806413, 1984016189},
    {-1518500250, 1518500250},
    {-1984016189, 821806413},
    {2147483647, 0},
    {2106220352, 418953276},
    {1984016189, 821806413},
    {1785567396, 1193077991},
    {1518500250, 1518500250},
    {1193077991, 1785567396},
    {821806413, 1984016189},
    {418953276, 2106220352},
    {0, 2147483647},
    {-418953276, 2106220352},
    {-821806413, 1984016189},
    {-1193077991, 1785567396},
    {-1518500250, 1518500250},
    {-1785567396, 1193077991},
    {-1984016189, 821806413},
    {-2106220352, 418953276},
    {2147483647, 0},
    {2137142927, 210490206},
    {2106220352, 418953276},
    {2055013723, 623381598},
    {1984016189, 821806413},
    {1893911494, 1012316784},
    {1785567396, 1193077991},
    {1660027308, 1362349204},
    {1518500250, 1518500250},
    {1362349204, 1660027308},
    {1193077991, 1785567396},
    {1012316784, 1893911494},
    {821806413, 1984016189},
    {623381598, 2055013723},
    {418953276, 2106220352},
    {210490206, 2137142927},
    {0, 2147483647},
    {-210490206, 2137142927},
    {-418953276, 2106220352},
    {-623381598, 2055013723},
    {-821806413, 1984016189},
    {-1012316784, 1893911494},
    {-1193077991, 1785567396},
    {-1362349204, 1660027308},
    {-1518500250, 1518500250},
    {-1660027308, 1362349204},
    {-1785567396, 1193077991},
    {-1893911494, 1012316784},
    {-1984016189, 821806413},
    {-2055013723, 623381598},
    {-2106220352, 418953276},
    {-2137142927, 210490206},
};

// Packed Q31 complex word of one stage twiddle: imaginary in bits 63..32,
// real in bits 31..0. Returns std::nullopt outside the frozen table so
// every consumer fails closed instead of extrapolating.
inline std::optional<uint64_t> getPackedQ31TwiddleBits(Q31TwiddleDirection direction, int64_t size,
                                                       int64_t index) {
  if (size < 2 || size > kMaxQ31TwiddleExtent || index < 0 || index >= size / 2)
    return std::nullopt;
  const Q31TwiddleComponents &entry = direction == Q31TwiddleDirection::Forward
                                          ? kForwardQ31Twiddles[size / 2 + index]
                                          : kInverseQ31Twiddles[size / 2 + index];
  return (static_cast<uint64_t>(static_cast<uint32_t>(entry.imaginary)) << 32) |
         static_cast<uint64_t>(static_cast<uint32_t>(entry.real));
}

} // namespace ondrix

#endif // ONDRIX_SUPPORT_Q31TWIDDLETABLES_H
